/* DDL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO INT NOT NULL,
    FRETE DECIMAL(10,2) NOT NULL
);

/* ALTER TABLE */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */

ALTER TABLE PRODUTO CHANGE VALOR_UNITARIO PRECO FLOAT(10,2) NOT NULL;

/* MODIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO MODIFY FRETE FLOAT(10,2) NOT NULL;

/* ADCIONANDO COLUNAS */

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL;

/* APAGANDO CLUNAS */

ALTER TABLE PRODUTO
DROP PESO;

/* ADCIONANDO UMA COLUNA APOS UMA COLUNA ESPECIFICA */

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL 
AFTER NOME_PRODUTO; 

ALTER TABLE PRODUTO
ADD ESTOQUE INT NOT NULL
FIRST;