SELECT COUNT(*) FROM CLIENTES;

SELECT COUNT(*) AS "TOTAL DE CLIENTES" FROM CLIENTES;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/*UPDATE PARA ATUALIZAR DADOS*/
UPDATE CLIENTE SET MAIL = '';

/*WHERE VAI SERVIR MUITO*/

UPDATE CLIENTE SET EMAIL = '' WHERE NOME = '';