/* Modelagem Básica - 

ENTIDADE=TABELA
CAMPOS - ATRIBUTOS

*/

CLIENTE

NOME - CHAR(30)
CPF - INTEGER(11)
EMAIL - CHAR(30)
TELEFONE - INTEGER(30)
ENDEREÇO - CHAR(30)
SEXO - BOOLEAN(1)

/*PROCESSOS DE MODELAGEM*/

/*FASE 01 E FASE 02 - AD ADM DE DADOS*/
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/*FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE DADOS

/* INICIANDO A MODELAGEM FÍSICA*/
/*CRIANDO O BANCO DE DADOS*/

CREATE DATABASE PROJETO;

/*CONECTANDO-SE AO BANCO */
USE PROJETO;

/*CRIANDO A TABELA CLIENTES*/
CREATE TABLE CLIENTE(
	NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDERECO VARCHAR (100) /*Não há vírgula após a ÚLTIMA cOLUNA*/
);

/* VERIFICANDO AS TABELAS DO BANCO*/
SHOW TABLES;

/*DESCOBRINDO COMO É A ESTRUTURA DE UMA TABLEA*/
DESC CLIENTE;

/*FORMA 01 - OMITINDO AS COLUNAS*/
INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MARIA LACERDA - ESTACIO 
- RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, 
'25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES('JORFE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO 
- PATOS DE MINAS - MG');

/*FORMA 02 - COLOCANDO AS COLUNAS - FORMA MAIS SEGURA*/
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA', 'F', 'SENADOR SOARES - 
TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/*O COMANDO SELECT
SELEÇÃO PROJEÇÃO E JUNÇÃO
*/

/*SELECT -> PROJEÇÃO*/
SELECT NOW() as DATA_HORA, 'EROS' AS ESTUDANTE;
SELECT 'EROS SIMETTE';
SELECT 'BANCO DE DADOS';

/*ALIAS DE COLUNA*/
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, ENDERECO, NOME FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/*APENAS PARA FINS ACADEMICOS*/
SELECT * FROM CLIENTE;

/*FILTRANDO DADOS COM WHERE E LIKE*/
SELECT NOME, TELEFONE FROM CLIENTE;

/*FILTRANDO*/
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/*UTILIZANDO O LIKE*/
SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE 'RJ';

/*CARACTER CORINGA % -> QUALQUER COISA*/
SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE '%CENTRO%';