CREATE DATABASE LIVRARIA;

/*
NOME DO LIVRO
NOME DO AUTOR
SEXO DO AUTOR
NUMERO DE PÁGINAS 
NOME DA EDITORA
VALOR DO LIVRO
ESTADO(UF) DA EDITORA
ANO PUBLICADO
*/

USE LIVRARIA;

CREAT TABLE LIVROS{
	NOMELIV VARCHAR (100),
	NOMEAUT VARCHAR (100),
	SEXOAUT CHAR (1),
	NUMPAG INT (5),
	NOMEEDIT VARCHAR (30),
	VALORLIV FLOAT (10,2),
	UFEDIT CHAR (2),
	ANOPUBLIV INT (4)
}